feat: add bashly to maintain bash script easily

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,68 +1,307 @@
-#!/bin/bash
-ssh_priv_key="$HOME/.ssh/id_ed25519"
-ssh_pub_key="$ssh_priv_key.pub"
-gitlab_hosts=1
-use_ssh="true"
+#!/usr/bin/env bash
+# This script was generated by bashly 1.1.10 (https://bashly.dannyb.co)
+# Modifying it manually is not recommended
 
-usage() { 
-  echo "Usage: $0 [ -t ] [ -h ] [ -g GITLAB_HOSTS ]" 1>&2 
-  echo ' -h This help message' 1>&2
-  echo ' -t Do not use ssh when testing' 1>&2 
-  echo ' -g Takes a number to loop through setting up gitlab hosts' 1>&2
+# :wrapper.bash3_bouncer
+if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
+  printf "bash version 4 or higher is required\n" >&2
+  exit 1
+fi
+
+# :command.master_script
+# :command.root_command
+root_command() {
+  # src/root_command.sh
+  echo "# this file is located in 'src/root_command.sh'"
+  echo "# you can edit it freely and regenerate (it will not be overwritten)"
+  inspect_args
+  sudo yum install -y keepassxc git gh glab ansible ansible-core
+  git clone https://github.com/brightly-ccv/0-config
+  cd bootstrap-config
+
+  if [ $test == 'true' ];
+  	then
+  	if [ ! -f "$ssh_priv_key" ];
+  	then
+  		mkdir -p -m 700 ~/.ssh
+  		ssh-keygen -t ed25519 -f "$ssh_priv_key"
+  		eval `ssh-agent -s`; ssh-add
+  	fi
+  	gh auth login -h github.com -p ssh -w -s admin:public_key
+  	for amount in {1..$gitlab_hosts}
+  	do
+  		glab auth login -h $host
+          	glab config set gitlab_host "$host"
+          	glab ssh-key add -t "main driver" "$ssh_pub_key"
+  	done
+  fi
+
+  ansible-playbook -i localhost, --connection=local -b configure.yml
+
+  if [ $use_ssh == 'true' ]; then
+  	source "$HOME/.cargo/env"
+  	eval `ssh-agent -s`; ssh-add
+  	chezmoi init --apply git@github.com:brightly-ccv/dotfiles.git
+  	grm repos sync config --config ~/.config/grm/config.toml
+  fi
+  echo "run 'source $HOME/.cargo/env' if you want to enable rust tools in this session"
+
 }
 
-while getopts "tg:h" options; do 
-	case "${options}" in 
-		t)
-			use_ssh="false"
-			;;
-		g)
-			gitlab_hosts=${OPTARG}
-			;;
-		h)
-			usage
-			exit 0
-			;;
-		:)
-			echo "Error: -${OPTARG} requires an argument."
-			usage
-			exit 1
-			;;
-		*)
-			usage
-			exit 1
-			;;
-	esac
-done
+# :command.version_command
+version_command() {
+  echo "$version"
+}
 
-sudo yum install -y keepassxc git gh glab ansible ansible-core
+# :command.usage
+run_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "run - Bootstrap Config\n"
+    echo
 
-git clone https://github.com/brightly-ccv/bootstrap-config.git
-cd bootstrap-config 
+  else
+    printf "run - Bootstrap Config\n"
+    echo
 
-if [ $use_ssh == 'true' ]; 
-	then
-	if [ ! -f "$ssh_priv_key" ]; 
-	then
-		mkdir -p -m 700 ~/.ssh
-		ssh-keygen -t ed25519 -f "$ssh_priv_key"
-		eval `ssh-agent -s`; ssh-add
-	fi
-	gh auth login -h github.com -p ssh -w -s admin:public_key
-	for amount in {1..$gitlab_hosts}
-	do 
-		glab auth login -h $host
-        	glab config set gitlab_host "$host"
-        	glab ssh-key add -t "main driver" "$ssh_pub_key"
-	done 
-fi
+  fi
 
-ansible-playbook -i localhost, --connection=local -b configure.yml
+  printf "%s\n" "Usage:"
+  printf "  run [OPTIONS]\n"
+  printf "  run --help | -h\n"
+  printf "  run --version | -v\n"
+  echo
 
-if [ $use_ssh == 'true' ]; then
-	source "$HOME/.cargo/env"
-	eval `ssh-agent -s`; ssh-add
-	chezmoi init --apply git@github.com:brightly-ccv/dotfiles.git
-	grm repos sync config --config ~/.config/grm/config.toml
-fi
-echo "run 'source $HOME/.cargo/env' if you want to enable rust tools in this session"
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--test, -t TEST"
+    printf "    Username to use for logging in\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--gitlab_hosts, -g GITLAB_HOSTS"
+    printf "    Password to use for logging in\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+    printf "  %s\n" "--version, -v"
+    printf "    Show version number\n"
+    echo
+
+    # :command.usage_environment_variables
+    printf "%s\n" "Environment Variables:"
+
+    # :environment_variable.usage
+    printf "  %s\n" "PRIVATE_SSH_KEY"
+    printf "    Set private ssh key path\n"
+    printf "    Default: $HOME/.ssh/id_ed25519\n"
+    echo
+
+    # :environment_variable.usage
+    printf "  %s\n" "PUBLIC_SSH_KEY"
+    printf "    Set public ssh key path\n"
+    printf "    Default: $HOME/.ssh/id_ed25519.pub\n"
+    echo
+
+  fi
+}
+
+# :command.normalize_input
+# :command.normalize_input_function
+normalize_input() {
+  local arg flags passthru
+  passthru=false
+
+  while [[ $# -gt 0 ]]; do
+    arg="$1"
+    if [[ $passthru == true ]]; then
+      input+=("$arg")
+    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
+      input+=("${BASH_REMATCH[1]}")
+      input+=("${BASH_REMATCH[2]}")
+    elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
+      input+=("${BASH_REMATCH[1]}")
+      input+=("${BASH_REMATCH[2]}")
+    elif [[ $arg =~ ^-([a-zA-Z0-9][a-zA-Z0-9]+)$ ]]; then
+      flags="${BASH_REMATCH[1]}"
+      for ((i = 0; i < ${#flags}; i++)); do
+        input+=("-${flags:i:1}")
+      done
+    elif [[ "$arg" == "--" ]]; then
+      passthru=true
+      input+=("$arg")
+    else
+      input+=("$arg")
+    fi
+
+    shift
+  done
+}
+
+# :command.inspect_args
+inspect_args() {
+  if ((${#args[@]})); then
+    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
+    echo args:
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${args[$k]} = ${args[$k]}"
+    done
+  else
+    echo args: none
+  fi
+
+  if ((${#other_args[@]})); then
+    echo
+    echo other_args:
+    echo "- \${other_args[*]} = ${other_args[*]}"
+    for i in "${!other_args[@]}"; do
+      echo "- \${other_args[$i]} = ${other_args[$i]}"
+    done
+  fi
+
+  if ((${#deps[@]})); then
+    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
+    echo
+    echo deps:
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${deps[$k]} = ${deps[$k]}"
+    done
+  fi
+
+  if ((${#env_var_names[@]})); then
+    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
+    echo
+    echo "environment variables:"
+    for k in "${sorted_names[@]}"; do
+      echo "- \$$k = ${!k:-}"
+    done
+  fi
+}
+
+# :command.user_lib
+# src/lib/sample_function.sh
+sample_function() {
+  echo "it works"
+}
+
+# :command.command_functions
+
+# :command.parse_requirements
+parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --version | -v)
+        version_command
+        exit
+        ;;
+
+      --help | -h)
+        long_usage=yes
+        run_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.environment_variables_filter
+  # :command.environment_variables_default
+  export PRIVATE_SSH_KEY="${PRIVATE_SSH_KEY:-$HOME/.ssh/id_ed25519}"
+  export PUBLIC_SSH_KEY="${PUBLIC_SSH_KEY:-$HOME/.ssh/id_ed25519.pub}"
+
+  env_var_names+=("PRIVATE_SSH_KEY")
+  env_var_names+=("PUBLIC_SSH_KEY")
+
+  # :command.command_filter
+  action="root"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --test | -t)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--test']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--test requires an argument: --test, -t TEST" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --gitlab_hosts | -g)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--gitlab_hosts']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--gitlab_hosts requires an argument: --gitlab_hosts, -g GITLAB_HOSTS" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.initialize
+initialize() {
+  version="0.1.0"
+  long_usage=''
+  set -e
+
+  # :command.environment_variables_default
+  export PRIVATE_SSH_KEY="${PRIVATE_SSH_KEY:-$HOME/.ssh/id_ed25519}"
+  export PUBLIC_SSH_KEY="${PUBLIC_SSH_KEY:-$HOME/.ssh/id_ed25519.pub}"
+
+}
+
+# :command.run
+run() {
+  declare -A args=()
+  declare -A deps=()
+  declare -a other_args=()
+  declare -a env_var_names=()
+  declare -a input=()
+  normalize_input "$@"
+  parse_requirements "${input[@]}"
+
+  case "$action" in
+    "root") root_command ;;
+  esac
+}
+
+initialize
+run "$@"
